### PR TITLE
Use PHP syntax highlighting for .inc files

### PR DESCRIPTION
**Pull request by szepeviktor**
Just that.

Now they have a black-and-white look.

### CODE REVIEW

**Comment by jrfnl** [comment]
Interesting. I've never seen this setting before. Could you point me to the documentation of it ?

**Comment by szepeviktor** [comment]
Here it is, Juliette.
https://github.com/github/linguist/blob/master/docs/overrides.md#summary

**Comment by jrfnl** [comment]
> Here it is, Juliette. https://github.com/github/linguist/blob/master/docs/overrides.md#summary

Thanks Victor. I've had a look at that document and AFAICS it appears to be a GitHub specific feature, which is not [officially supported](https://git-scm.com/docs/gitattributes). Correct ?

I'm also in two minds about the principle of it for PHPCS standard repos:
* Yes, it is nice to see the test case files being properly highlighted and would make the test code more easily readable.
* No, the test case files are not code to be reviewed in the same way as sniff code or even read in the same way.
    Test case files will in most cases contain nonsense code and often contain (intentional) parse errors to make sure the sniff handles those correctly.
    I'm afraid that highlighting those files as "ordinary" PHP files will create more confusion and potential problems (GitHub marking lines as parse errors) than it's worth.
    
I'm going to have to think this over for a while....

**Comment by szepeviktor** [comment]
Seems like this helps, .inc files are full of colors 🎨
https://github.com/PHPCSStandards/PHPCSExtra/blob/c8ba5b37f9a214c4ee6db88b469cf1d0cee80054/.gitattributes#L33

**Comment by jrfnl** [comment]
> Seems like this helps, .inc files are full of colors

Not sure what you mean by that ?

**Comment by szepeviktor** [comment]
.inc files look like this

image

**Comment by jrfnl** [comment]
.. which is okay, as long as it doesn't start annotating "parse errors" and such.

**Pull request closed without merging**
